title: Muhammad Irtaza
bio: A Video Editor and Game Developer
# twitter summary info
description: A blog about technology and stuff related
external-image: false
picture: assets/images/profile.jpg
dark-theme: auto
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume
url: https://irtaza2009.github.io/indigo
permalink: /:title/
analytics-google: G-HHFKYQEHMW

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: github # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

#facebook: myfacebook
#twitter: mytwitter
instagram: irtaza_2009
#linkedin: mylinkedin
github: Irtaza2009
itch: irtaza
email: irtazanaqvi05@gmail.com

authors:
  irtaza:
    name: Muhammad Irtaza
    bio: I love to develop and play games
    external-image: false
    picture: assets/images/profile.jpg
    twitter: 

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended
#projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
